name: Deploy website

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]
      
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
      
    - name: Build Project
      run: |
        npm install
        npm run build
        npm run export
    
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.webne.com.br
        username: "webne"
        password: ${{ secrets.LOCAWEB_FTP_PASSWORD }}
        local-dir: ${{ github.workspace }}/out/
        server-dir: public_html/tiagooamaral/